//// <auto-generated />
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using MobileShop.Data;

//#nullable disable

//namespace MobileShop.Migrations
//{
//    [DbContext(typeof(MobileDbContext))]
//    [Migration("20221019063250_second")]
//    partial class second
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.10")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("MobileShop.Models.Mobile", b =>
//                {
//                    b.Property<int>("MobileId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobileId"), 1L, 1);

//                    b.Property<int>("Cost")
//                        .HasColumnType("int");

//                    b.Property<string>("Model")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RAM")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("MobileId");

//                    b.ToTable("Mobiles");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
